package com.gerrysatria.cinelist.model

import com.gerrysatria.cinelist.R

object MovieDataSource {
    val dataMovie = listOf(
        Movie(1,
            R.drawable.efnaf,
            "Five Nights at Freddy's",
            "A troubled security guard begins working at Freddy Fazbear's Pizza. During his first night on the job, he realizes that the night shift won't be so easy to get through. Pretty soon he will unveil what actually happened at Freddy's.",
            "1h 49m",
            5.5),
        Movie(2,
            R.drawable.kotfmf,
            "Killers of the Flower Moon",
            "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one - until the FBI steps in to unravel the mystery.",
            "3h 26m",
            8.0),
        Movie(3,
            R.drawable.ph,
            "Pain Hustlers",
            "Liza dreams of a better life for herself and her daughter. Hired to work for a bankrupt pharmaceutical company, Liza skyrockets with sales and into the high life, putting her in the middle of a federal criminal conspiracy.",
            "2h 2m",
            6.5),
        Movie(4,
            R.drawable.ahive,
            "A Haunting in Venice",
            "In post-World War II Venice, Poirot, now retired and living in his own exile, reluctantly attends a seance. But when one of the guests is murdered, it is up to the former detective to once again uncover the killer.",
            "1h 43m",
            6.6),
        Movie(5,
            R.drawable.tk,
            "The Killer",
            "After a fateful near-miss, an assassin battles his employers, and himself, on an international manhunt he insists isn't personal.",
            "1h 58m",
            7.4),
        Movie(6,
            R.drawable.nhf,
            "No Hard Feelings",
            "On the brink of losing her home, Maddie finds an intriguing job listing: helicopter parents looking for someone to bring their introverted 19-year-old son out of his shell before college. She has one summer to make him a man or die trying.",
            "1h 43m",
            6.4),
        Movie(7,
            R.drawable.op,
            "Oppenheimer",
            "The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
            "3h 0m",
            8.5),
        Movie(8,
            R.drawable.ttm,
            "Talk to Me",
            "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
            "1h 35m",
            7.2),
        Movie(9,
            R.drawable.pt,
            "Poor Things",
            "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
            "2h 21m",
            8.5),
        Movie(10,
            R.drawable.sx,
            "Saw X",
            "A sick and desperate John travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer only to discover the entire operation is a scam to defraud the most vulnerable.",
            "1h 58m",
            6.7),
        Movie(11,
            R.drawable.sc,
            "Scream",
            "25 years after a streak of brutal murders shocked the quiet town of Woodsboro, Calif., a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.",
            "1h 54m",
            6.3),
        Movie(12,
            R.drawable.smatsv,
            "Spider-Man: Across the Spider-Verse",
            "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
            "2h 20m",
            8.7),
        Movie(13,
            R.drawable.pr,
            "Priscilla",
            "When teenage Priscilla Beaulieu meets Elvis Presley, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments: a thrilling crush, an ally in loneliness, a vulnerable best friend.",
            "1h 53m",
            7.1),
        Movie(14,
            R.drawable.teb,
            "The Exorcist: Believer",
            "When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, who's been forever altered by what happened to her daughter fifty years ago.",
            "1h 51m",
            4.9),
        Movie(15,
            R.drawable.tn2,
            "The Nun II",
            "1956 - France. A priest is murdered. An evil is spreading. The sequel to the worldwide smash hit follows Sister Irene as she once again comes face-to-face with Valak, the demon nun.",
            "1h 50m",
            5.6),
        Movie(16,
            R.drawable.bar,
            "Barbie",
            "Barbie suffers a crisis that leads her to question her world and her existence.",
            "1h 54m",
            7.0),
    )
}